title: Kardel's Note
description: 一個平凡的工程師，紀錄著自我學習的過程，還有生活中的點滴
baseurl: "" # 如果是根目錄就留空
url: "https://kardelhuang.github.io"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
markdown: kramdown
highlighter: rouge
search_enabled: true
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
